apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-ourdbmdc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-ourdbmdc 
  name: go-ourdbmdc
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-ourdbmdc
    weight: 100 
